version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - name: finf
    repository:
      owner: ArturBobotcko  # Replace with your GitHub username
      name: homebrew-finf   # The name of the Homebrew tap repository
      
    # You can adjust these fields if you need specific archive IDs
    ids: 
      - finf_Linux_x86_64
      - finf_Windows_x86_64
      - finf_Darwin_x86_64

    # Optional: Specify the version of GOARM if needed
    goarm: 6

    # Optional: GOAMD64 if you need to specify a specific version of amd64
    goamd64: v1

    # URL for the artifacts, assuming this structure for your GitHub releases
    url_template: "https://github.com/ArturBobotcko/finf/releases/download/{{ .Tag }}/finf_{{ .Os }}_{{ .Arch }}.tar.gz"

    # Optional headers for the URL (if authentication is needed)
    url_headers:
      - "Accept: application/octet-stream"
      - 'Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}'

    # Optional: Custom download strategy
    download_strategy: CurlDownloadStrategy

    # Optional: Custom code block for formula
    custom_require: custom_download_strategy

    # Commit author for updates to the formula
    commit_author:
      name: ArturBobotcko
      email: artur.bobotcko@mail.ru

    # Commit message template
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"

    # Directory for the formula within the tap repo
    directory: Formula

    # Optional: Caveats for the user (installation instructions, etc.)
    caveats: "This is the finf CLI tool."

    # Optional: Description of the app
    description: "CLI tool for displaying file information."

    # License
    license: "MIT"

    # Skip upload if the release is a prerelease or in specific conditions
    skip_upload: false

    # Optional: Custom block for brew to handle special cases like head releases
    custom_block: |
      head "https://github.com/ArturBobotcko/finf.git"
    
    # Optional: List dependencies for the formula
    dependencies:
      - name: git
      - name: go

    # Optional: Conflicts with other packages
    conflicts:
      - svn

    # Optional: Add service or plist block for Homebrew services
    service: |
      run: finf

    # Optional: Test block for brew
    test: |
      system "#{bin}/finf --version"
    
    # Optional: Install script to modify the default behavior
    install: |
      bin.install "finf"
    
    # Optional: Additional instructions for installation
    extra_install: |
      bash_completion.install "completions/finf.bash" => "finf"
    
    # Optional: Post-installation script
    post_install: |
      etc.install "finf-config.conf"
